name: deepLearn_V3
channels:
  - defaults
dependencies:
  - ipykernel=4.8.2
  - python=3.6.5
  - matplotlib=2.2.2
  - numpy=1.14.3
  - pandas=0.23.0
  - seaborn=0.8.1
  - scipy=1.1.0
  - sqlite=3.23.1
  - numba=0.38.0
  - scikit-learn=0.19.1
  - pip
  - pip:
      - keras==2.1.5
      - tensorboard==1.6.0
      - tensorflow-gpu==1.6.0